AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  injoyeventdetails:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.10
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::365472796140:role/injoy_events_role'
      VpcConfig:
        SecurityGroupIds:
          - sg-0ba29ca275a72f86e
          - sg-026be2bc1b8663c8d
        SubnetIds:
          - subnet-0b3771856249cb94b
          - subnet-0c1ca39804cfbbfd9
      Layers:
        - 'arn:aws:lambda:us-east-1:365472796140:layer:pymysql:1'
        - 'arn:aws:lambda:us-east-1:365472796140:layer:mysql:2'
        - 'arn:aws:lambda:us-east-1:365472796140:layer:mylayer:1'
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
